### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by anbc** [wgliang/Codeeye#1]
建议增加一个使用手册，具体传入什么参数，结果去哪里看。最好有一个具体的例子。没太研究，直接使用的，应该是用法不对。

D:\run\Codeeye-master\src>python codeeye.py -p "D:\work\USM\security_display\trunk\security_monitor_new\src"
Traceback (most recent call last):
  File "codeeye.py", line 25, in <module>
    oper.json_init(rpath+'/conf/codeeye.json')
  File "D:\run\Codeeye-master\src\oper.py", line 137, in json_init
    data = jsonconf.read_json(path)
  File "D:\run\Codeeye-master\src\jsonconf.py", line 5, in read_json
    f = file(path)
IOError: [Errno 2] No such file or directory: 'D:\\work\\USM\\security_display\\trunk\\security_monitor_new\\src/conf/codeeye.json'

**Comment by wgliang** [comment]
不好意思，这是几年前写的一个玩具项目，没有使用手册。。。
